sudo: false
language: cpp
dist: trusty
matrix:
  include:
    - os: linux
      env: PYTHON=2.7
addons:
  apt:
    # sources:
    #   - ubuntu-toolchain-r-test
    packages:
      # - g++-4.9
      # - gcc-4.9
      - libboost-dev
  env:
    - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python$PYTHON venv
  - source venv/bin/activate
install:
  - pip install -r requirements.txt
  - python setup.py sdist
  - pip install --verbose dist/*.tar.gz
script:
  - /bin/bash test/build_models.sh
  - nosetests -v
