sudo: false
language: python
python:
  - "2.7"
  # - "3.4"
  # - "3.5"
  # - "3.6"
# command to install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
      - libboost-dev
  env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - pip install -r requirements.txt
script:
  - g++ --version
  - python setup.py install
  - /bin/bash test/build_models.sh
  - python setup.py test
