sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
addons:
  apt:
    packages:
      - libboost-dev
install:
  - pip install -r requirements.txt
script:
  - python setup.py install
  - /bin/bash test/build_models.sh
  - python setup.py test
